In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
a1 = np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a1.shape

(5,)

In [ ]:
a2 =np.array([[1,2,3,4],[5,6,7,8]])
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
type(a2)

numpy.ndarray

In [ ]:
a2.shape

(2, 4)

In [ ]:
a2.size

8

In [ ]:
a2.ndim

2

In [ ]:
a3 = np.array([[[1,2,3,],[5,6,7,],[9,10,11,]]])
print(a3)

[[[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]]]


In [ ]:
a3.size

9

In [ ]:
a3.ndim

3

In [ ]:
a3.shape

(1, 3, 3)

In [ ]:
z1 = np.zeros(3)
z1

array([0., 0., 0.])

In [ ]:
z1 = np.zeros(3 ,dtype = int)
z1

array([0, 0, 0])

In [ ]:
z1.shape

(3,)

In [ ]:
z1.ndim

1

In [ ]:
type(z1)

numpy.ndarray

In [ ]:
z2 = np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
z2 = np.zeros((3,4),dtype = int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
type(z2)

numpy.ndarray

In [ ]:
z2.shape

(3, 4)

In [ ]:
z3 = np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
z3 = np.zeros((2,3,4),dtype=int)
z3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
z3.size

24

In [ ]:
z3.shape

(2, 3, 4)

In [ ]:
a1 = np.ones(5)
a1

array([1., 1., 1., 1., 1.])

In [ ]:
a2 = np.ones([3,4])
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a3 = np.ones([4,2,3])
a3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
type(a3)

numpy.ndarray

In [ ]:
a3.shape

(4, 2, 3)

In [ ]:
a3.size

24

In [ ]:
f1 = np.full(3,9)
f1

array([9, 9, 9])

In [ ]:
f1 = np.full([2,3],9)
f1

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
f3 = np.full([4,2,3],10)
f3

array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])

In [ ]:
a = np.array([1,2,3])
b = np.array([1,2,3])

add = np.add(a,b)
add

array([2, 4, 6])

In [ ]:
a = np.array([5,10,20])
b = np.array([4,8,10])

sub = np.subtract(a,b)
sub

array([ 1,  2, 10])

In [ ]:
a = np.array([5,10,20])
b = np.array([4,8,10])

mul = np.multiply(a,b)
mul

array([ 20,  80, 200])

In [ ]:
a = np.array([5,10,20])
b = np.array([4,8,10])

div = np.divide(a,b)
div

array([1.25, 1.25, 2.  ])

In [ ]:
a = np.array([5,10,20])
b = np.array([4,8,10])

sub = np.mod(a,b)
sub

array([1, 2, 0])